name: Tests

on: # Cada vez que se intente hacer push o merge
    push:
        branches:
            - develop
            - main

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version-file: pubspec.yaml # Usa la versión de flutter indicada en el pubspec

            - name: Install dependencies
              run: flutter pub get

            - name: Run Integration Tests 
              run: flutter test integration_test # Solo ejecuta los tests de integración
            